Get rid of throwing same errors in loop
opentdf/opentdf pull request #139
Opened 2022-08-31 13:26 UTC by krokhmaliuk-virtru

2022-09-08 13:22 UTC, dmihalcik-virtru requested changes

2022-09-08 13:22 UTC, dmihalcik-virtru commented on examples/webcam-app/src/containers/HomePage/HomePage.tsx
> +                            errorMap.current[userName] = true;
The `catch` lambda here can be placed in the `catch` clause below. Adding a .catch here coverts the `Promise<ArrayBuffer>` to `Promise<ArrayBuffer | void>` I think? anyway, it will still throw when incominbbuffer is dereferenced and then that will get ignored.

2022-09-08 13:22 UTC, dmihalcik-virtru commented on examples/webcam-app/src/containers/HomePage/HomePage.tsx
> +                    // @ts-ignore
What are these ts-ignores doing?

2022-09-08 13:37 UTC, obidenko approved these changes

2022-09-08 13:37 UTC, obidenko commented on examples/webcam-app/src/hooks/useLogin.ts
> -        organizationName: OIDC_REALM
Isn't it required?

2022-09-15 13:14 UTC, dmihalcik-virtru approved these changes

2022-09-29 14:53 UTC, dmihalcik-virtru approved these changes

2022-09-29 14:53 UTC, dmihalcik-virtru commented on examples/webcam-app/src/config/index.ts
>  export const OIDC_REALM = "tdf";
Can you get rid of this variable entirely now?

2022-09-29 14:53 UTC, dmihalcik-virtru commented on examples/webcam-app/src/containers/HomePage/HomePage.tsx
> +        //@ts-ignore
Please add a note here about why you are using ts-ignore

2022-09-29 15:25 UTC, dmihalcik-virtru submitted a review, later dismissed

2022-09-30 12:26 UTC, pflynn-virtru approved these changes

2022-09-30 12:44 UTC, merged