WIP [Do not merge] - Bring up the secure-remote-storage hero app via tilt up
opentdf/opentdf pull request #88
Opened 2022-07-06 21:22 UTC by danielRicaud

…rror on upload

2022-07-12 22:37 UTC, danielRicaud commented on examples/secure-remote-storage/src/App.js
> +        .withStreamSource(toWebReadableStream(fileReaderStream(selectedFile)))
If `web-streams-node` doesn't break locker compliance I'll prob add a `.withNodeStreamSource()` method so users don't have to worry about this themselves, or I'll have `.withStreamSource()` auto detect and try to convert it internally to not expand the API more than necessary.

2022-07-12 22:38 UTC, danielRicaud commented on examples/secure-remote-storage/src/components/UserStatus/UserStatus.css
> +.oidc-avatar {
Keep the naming generic or descriptive?

2022-07-12 22:38 UTC, danielRicaud commented on quickstart/helm/values-keycloak.yaml
> +    value: h2
Is this acceptable since it's a `quickstart`? Switching to H2?

2022-07-12 23:31 UTC, elizabethhealy commented on quickstart/helm/values-keycloak.yaml
> +    value: h2
since the DB_ADDR issue, across the board, is something that we've only seen pop up occasionally, i would vote to not include this or keep it commented out and add something to the troubleshooting docs

2022-07-13 14:25 UTC, dmihalcik-virtru commented on examples/secure-remote-storage/src/App.js
> +        .withStreamSource(toWebReadableStream(fileReaderStream(selectedFile)))
generally we are trying to move away from builders to a more functional style - the auth code is an example of what I'd like. 

1. This lets the code be tree shakable, as current tree shaking code can't eliminate methods from a class.
2. This is compatible with async methods to construct helper objects, which we had trouble with in the past iirc
3. For this specific method, the web-streams-node package is only required for node < 16.5, as it is built-in after that (if marked *experimental*)

2022-07-13 14:26 UTC, dmihalcik-virtru commented on examples/secure-remote-storage/src/components/UserStatus/UserStatus.css
> +.oidc-avatar {
why not just avatar?

2022-07-13 15:10 UTC, obidenko requested changes

2022-07-13 15:48 UTC, danielRicaud commented on examples/secure-remote-storage/Dockerfile
> +COPY package-lock.json package.json opentdf-client-0.2.2.tgz ./
oh awesome thanks!!!

2022-07-13 15:49 UTC, danielRicaud commented on quickstart/helm/values-keycloak.yaml
> +    value: h2
Sick! Ill remove this and make a separate PR that only does this H2 switch so it can be it's own decision! I'd probably need someone to sanity check using Postgres since it seems to really not like my local env.

2022-07-14 16:20 UTC, danielRicaud commented on examples/secure-remote-storage/src/App.js
> +        .withStreamSource(toWebReadableStream(fileReaderStream(selectedFile)))
Node automatically transforms node streams to web streams now? Also should our builder method be called .withWebStreamSource to give the user a hint?

2022-07-15 15:26 UTC, merged